language: node_js
sudo: required
dist: trusty
node_js: stable
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --skip-plugin local; fi
env:
  global:
  - secure: GBydovTcXOXwpCLj4eAOW2KZi0RZHinq3EG86GU+mQdA0o0zbw9gZUgwUl8PC166cYVHPa42siJLy+XNwedjleY6DWKLIBjHUV4jalCtGroIPd7b5deOwq1Qd9m5tDQ3rpkfeVr1pR8C5MAcDm0yeBQx4BBhy+ndDHWbje45LD3nFakvDPe1QYZoGyz+8nYhD9emznFzIufCpH+MZy+6E5aXEgMZNyb9YvEfw4YD7qCL8Swb8MSlrrUSjKkSmVNtnamh7o+JhKzL16g3qnfKhiCyrLo6N8MDF7DIWVkG11+NQMJb0D4P/HGlvU5SwHSJtJiaLktLflOyvTqyfkXUXDizWWbzCB1QEPCmhTF8PRFxuKPZz8LiPZqg10vhpDwxa/c/3O/EKfN/RS3T1pA0t2Z+i4GhJoDomG8rBlzvnlIjCumcD4Q//zZKIyqNxEiFjNI6JHdeoMhV74J1ncFyW8DZDI4UEARAqk6j5UMBG46+7sRrtK/ZaMQgQH5iFxsA74spx1tt8KTBsuN3rFWmfRMytkktpvfD8ajckgk5JOVsZfrIAGl1IIAmPZQwvEpVlGAMNT9uT18DtRNr+6G1eUq20cKyAlW/FDJabgAtzNmeJQ/r1V1+Vu+RMBUanS/akNRjDuigKY2gp1afvUQ4AZowCkFCbqvh6tLZBt2ZETI=
  - secure: SAR+ZyM0SMOqKWkCg1mvQtCmIXvtrVz8uWmvw2js32isJ7QVZMh8ZZ/dVgCpJen4tSBXLWZ7lBTjG1pVI701r5zAK7ZBurSBGiJuxZer+UD0GeEEwsHw4hDGQZ9DYK1igoHiqztXMGNwf3nSj2TXZ2pNDp2aLeUeshGS+t49oZBj5LDXQ8QO5bMYfPlVSdFJqb2zmSHsGtmy8SFKyhl9/UnhzgIBDmes1rSpGwyU/bAIBAULAeRhTKAjqubmP2AZf+n+Y2DQAEMtD/p9L/F2kxgXjYLHEMEbbAOdMBQDu/atE/DqW1mSYqR/Sw48iTErN5F6VnGxlDaCWV24iipb5hs+N7LRkzeiCGCWDmuug5lOui1Fm0HdvoIZjxjyYy9bXJ4Je1iVr5tICGZ6DJmvIaB6Q9w8wTAOtEs25O2cR8F5oaPGw087EF/Ug73hzq6guM+9tes1bc2QpzRn5+hoVUw2/Bdx3cW1OeAuFiew3DfxEAZkcivzRNcYvUPuJQthhsjdZUrjznvh+0Gwd9swxTtb+iqIOmBip+JLMFwlHP1CTFZIfSq2eiDqdt22LhfvFxFvimx+oGWQmgTNWifKkJImwmGyq+AuTKiZ6VmyNQXxEWPoy8PMp2nI6QWZi0vHrvNBb2ksT/2AwjxGeBgptsefibAUc3zcgEksDScAr/o=
